  datasource:
    platform: sqlserver
    url: jdbc:sqlserver://localhost:1433;databaseName=ZSS
    username: sa
    password: admin123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
